### ISSUE TITLE
A lot of commands not working with Python 3.8

### ISSUE THREAD

**Issue by NathanTurnYT** [xMistt/fortnitepy-bot#203]
There are a bunch of commands that doesn't work. One of them is !promote as mentionned in #192. There are also !unhide, !set and !random. More commands also don't work and some don't work proprely but do the task. Im not gonna mention all of them tho.

I use Python 3.8.3 (I think, I know its 3.8 tho) and the latest version of the bot yet.

**Comment by Tommy3344** [comment]
Ok if commands are not working then use the recommended version (3.7). Simple as that

**Comment by xMistt** [comment]
To be completely honest, I haven't used PartyBot itself in months as I haven't even launched Fortnite in months. I will try and look into commands that don't work anymore later today but I will have to update my game first.

**Comment by xMistt** [comment]
I fixed !promote & !unhide in https://github.com/xMistt/fortnitepy-bot/commit/e37a877ee21c55e854ce9b6859a652a25f564b7d & I just recently fixed !set & !random in https://github.com/xMistt/fortnitepy-bot/commit/85d150695201635bab11ceb2959d8904218957bf. Please let me know if there is any other commands that no longer work. Also, the Python version had no correlation /w these commands being broken. It was due to broken changes in packages that PartyBot depends on that weren't accounted for as I didn't update PartyBot regularly for a long period of time.
